### ISSUE TITLE
Version Incorrectly Listed

### ISSUE THREAD

**Issue by greensad** [mineblock11/Woof#16]
W.O.O.F 3.0.0 is listed as for versions 1.19-1.19.3 when it only works on 1.19.3. Crashes on launch.

**Comment by MopsTMC** [comment]
Same goes for [mine11lib v0.1.5](https://modrinth.com/mod/mine11lib/version/0.1.5+1.19.3)

**Comment by mineblock11** [comment]
The version should already be clear on the curseforge pages.

**Comment by greensad** [comment]
On Modrinth it's shows this: ![image](https://user-images.githubusercontent.com/10079877/220718729-aaef4107-16d8-41e9-8c3e-559fbe92b8de.png)
